name: E2E

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - 'solutions/**'
      - 'assets/**'
      - 'troubleshooting/**'
      - ".github/ISSUE_TEMPLATE/*"
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.20'
  GO_REQUIRED_MIN_VERSION: ''

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          docker pull quay.io/zhujian/addon-examples:latest # TODO: REMOVE THIS LINE AFTER THE IMAGE IS CREATED BY ADDON-FRAMEWORK
          docker tag quay.io/zhujian/addon-examples:latest quay.io/open-cluster-management/addon-examples:latest
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-examples:latest
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
